#ifndef LIBSLEEK_GLOBAL_H
#define LIBSLEEK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBSLEEK_LIBRARY)
#  define LIBSLEEKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBSLEEKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBSLEEK_GLOBAL_H
